import React, { useEffect, useState } from 'react';
import IntroService from '../IntroService/IntroService';


const Services = () => {
    const [service, setService] = useState([]);
    useEffect(() => {
        fetch("./services.json")
            .then(res => res.json())
            .then(data => setService(data));
    },[])
    return (
        <div>
            <h1 className='my-5'>Our Treatments and Services</h1>
            <div className='container'>
                {
                    service.map(intro => <IntroService
                        key={intro.id}
                        intro={intro}
                    ></IntroService>)
                }
            </div>
        </div>
    );
};

export default Services;



// const jsonFile = [
//     {
//         id:1,
//         name: 'Acupressure',
//         price:64,
//         url: 'https://thumbs.dreamstime.com/b/chiropractic-osteopathy-manual-therapy-acupressure-chiropractic-osteopathy-manual-therapy-acupressure-therapist-doing-healing-117719800.jpg',
//         description:"Acupressure is an ancient healing art that's based on the traditional Chinese medicine practice of acupuncture. With acupressure, you put pressure on specific places on your body. These places are called acupoints. Pressing these points can help release muscle tension and promote blood circulation."
        
//     },
//     {
//         id:2,
//         name: 'Auriculo Therapy',
//         price:45,
//         url: 'https://i2.wp.com/acupuncturenutrition.com/wp-content/uploads/auriculotherapy-magnet-therapy.jpg?resize=1170%2C500&ssl=1',
//         description:"Auriculotherapy, also called auricular acupoint pressure or ear stimulation, is a method of diagnosing and treating diseases by stimulation of specific acupoints on the external ear, includes electrical stimulation, acupoint acupressure, different type of needles, seeds, and magnetic balls."
//     },
//     {
//         id:3,
//         name: 'Magnetotherapy',
//         price:70,
//         url: 'https://st2.depositphotos.com/6644020/11547/i/600/depositphotos_115470014-stock-photo-magnets-placed-to-patient-back.jpg',
//         description:"Magnetic therapy is a pseudoscientific alternative medicine practice involving the weak static magnetic field produced by a permanent magnet. It is similar to the alternative medicine practice of electromagnetic therapy, which uses a magnetic field generated by an electrically powered device."
//     },
//     {
//         id:4,
//         name: 'Reflexology',
//         price:60,
//         url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCDUHwY4UUPhWVS28aTgeGItxZa6sP8_ZZGg&usqp=CAU',
//         description:"Reflexology is the application of pressure to areas on the feet (or the hands). The theory behind reflexology is that areas of the foot correspond to organs and systems of the body. Pressure applied to the foot is believed to bring relaxation and healing to the corresponding area of the body."
//     },
//     {
//         id:5,
//         name: 'Moxibustion',
//         price:50,
//         url: 'https://cdn.britannica.com/w:400,h:300,c:crop/27/199927-050-85B901E3/moxibustion-cones-moxa-treatment-points-top-needles.jpg',
//         description:"Moxibustion is a form of therapy that entails the burning of mugwort leaves. This is a small, spongy herb that is believed to enhance healing with acupuncture. As such, the leaves are burnt close to the skin's surface using a stick to apply heat.‌ The practice is derived from Chinese medicine."
//     },
//     {
//         id:6,
//         name: 'Cupping therapy',
//         price:48,
//         url: 'https://www.muscleandfitness.com/wp-content/uploads/2018/07/cupping-man-1109.jpg?w=940&h=529&crop=1&quality=86&strip=all',
//         description:"Cupping therapy is a form of alternative medicine in which a local suction is created on the skin with the application of heated cups. Its practice mainly occurs in Asia but also in Eastern Europe, the Middle East, and Latin America. As with all alternative medicine, cupping has been characterized as a pseudoscience and its practice as quackery."
//     },
//     {
//         id:7,
//         name: 'Rehabilitation',
//         price:58,
//         url: 'https://www.knollwoodnursingcenter.com/wp-content/uploads/2019/09/nursing-home-vs-rehabilitation-center.png',
//         description:"Rehabilitation helps a child, adult or older person to be as independent as possible in everyday activities and enables participation in education, work, recreation and meaningful life roles such as taking care of family. It does so by addressing underlying conditions (such as pain) and improving the way an individual functions in everyday life."
//     },
//     {
//         id:8,
//         name: 'Hypothyroidism',
//         price:45,
//         url: 'https://tailormadehealth.com/wp-content/uploads/2019/02/woman-thyroid-glands-control-close-female-hypothyroidism-ss-Feature.jpg',
//         description:"Hypothyroidism is a common condition where the thyroid doesn't create and release enough thyroid hormone into your bloodstream. This makes your metabolism slow down. Also called underactive thyroid, hypothyroidism can make you feel tired, gain weight and be unable to tolerate cold temperatures."
//     },
//     {
//         id:9,
//         name: 'Samurai Massage',
//         price:70,
//         url: 'https://florida-academy.edu/wp-content/uploads/2020/05/Head-Massage-FloridaAcademy-scaled.jpeg',
//         description:"Massage used to be available only through luxury spas and upscale health clubs. Today, massage therapy is offered in businesses, clinics, hospitals and even airports. If you've never tried massage, learn about its possible health benefits and what to expect during a massage therapy session."
//     },
// ]



